language: generic 
sudo: required
services: 
  - docker

before_install:
  - docker build -t  Icaruis/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true  Icaruis/docker-react npm run test
